In [1]:
import matplotlib
import matplotlib.pyplot
import numpy as np

# utilities for importing from other Jupyter notebooks
import custom_utilities

# import code from the other Jupyter notebook
from Plotting import plot

from qutip import *
from scipy import *
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute, BasicAer
from QuantumMechanics import Ising, evolve, isingTrotter, confs

importing notebook from Plotting.ipynb
importing notebook from QuantumMechanics.ipynb
test_I <class 'qutip.qobj.Qobj'> Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
def 